
import type { Metadata } from 'next'
import './globals.css'
import LayoutPage from '@/components/Layout';

export const metadata: Metadata = {
  title: 'Next App Template',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body>
        <LayoutPage>
          {children}
        </LayoutPage>
      </body>
    </html>
  )
}
