
import type { Metadata } from 'next'
import './globals.css'
import { ConfigProvider } from 'antd';
import StyledComponentsRegistry from '../lib/AntdRegistry';
import theme from '../theme/themeConfig';
import LayoutPage from '@/components/Layout';

export const metadata: Metadata = {
  title: 'Next App Template',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body>
        <ConfigProvider theme={theme}>
          <StyledComponentsRegistry>
            <LayoutPage>
              {children}
            </LayoutPage>
          </StyledComponentsRegistry>
        </ConfigProvider>
      </body>
    </html>
  )
}
